coverage:
  precision: 2
  round: down
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

ignore:
  - "tests/**/*"
  - "build/**/*"

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
